version: "3.7"

services:
  download-playlist:
    image: ghcr.io/scrath1/yt-syncdl:latest
    container_name: download-yt-playlist
    environment:
      - DL="1pOBa1Cf1k8;ExampleWithVideoID;--format bestaudio --extract-audio"
      - CRON="* * * * *"
      - MAX_LOG_LINES=20
    volumes:
      - ./download:/download
      - ./log:/var/log/
